version: "1"

services:
  stupl-psql:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  stupl-backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=stupl-psql
    depends_on:
      - stupl-psql
  stupl-frontend:
    build: frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - API_HOST=stupl-backend
    depends_on:
      - stupl-backend
