version: "1"

services:
  stupl-backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - data:/data
  stupl-frontend:
    build: frontend
    ports:
      - "80:80"

volumes:
  data:
