version: "1"

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  react:
    build: frontend
    restart: always
    ports:
      - "80:3000"
