version: "1"

services:
  db:
    image: postgres
    volumes:
      - ../data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db
      - DJANGO_DEBUG=True
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - db
